===================================================================================================================
VERTICAL POD AUTOSCALING
===================================================================================================================
Deployment YAML (deployment.yaml)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: production
  labels:
    app: my-app
spec:
  replicas: 2        
  selector:
    matchLabels:
      app: my-app                     
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: myrepo/my-app:latest    
        ports:
        - containerPort: 8080
        resources:                    
          requests:
            cpu: "100m"                 # Guaranteed minimum CPU
            memory: "256Mi"             # Guaranteed minimum Memory
          limits:
            cpu: "500m"                 # Maximum CPU allowed
            memory: "512Mi"             # Maximum Memory allowed
        readinessProbe:                 # Checks if app is ready to receive traffic
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:                  # Checks if app is alive (restart if failed)
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
-----------------------------------------------------------------------------------------------------
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa
  namespace: production
spec:
  targetRef:                                 # Target deployment this VPA applies to
    apiVersion: "apps/v1"
    kind: Deployment
    name: my-app
  updatePolicy:
    updateMode: "Auto"                       # Modes: Auto, Off, Initial
  resourcePolicy:                            # (Optional) Limit min/max for VPA adjustments
    containerPolicies:
    - containerName: '*'                     # Apply to all containers
      minAllowed:
        cpu: "100m"
        memory: "256Mi"
      maxAllowed:
        cpu: "1000m"
        memory: "1Gi"



🔗 How They Work Together:
1. Deployment defines initial CPU/Memory requests and limits.
2. VPA observes real usage and automatically adjusts requests up or down.
3. VPA applies new requests by restarting pods (this is normal and necessary).
